# Generated by Django 4.0.6 on 2023-01-11 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
