# Generated by Django 4.0.6 on 2022-07-19 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='highlighted',
            field=models.BooleanField(default=True),
        ),
    ]
