# Generated by Django 4.0.6 on 2023-01-11 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_name', models.CharField(help_text='Necessário', max_length=255, verbose_name='Nome da entrega')),
                ('delivery_price', models.DecimalField(decimal_places=2, error_messages={'name': {'max_length': 'O preço deve estar entre 0 e 999.99'}}, help_text='Máximo 999.99', max_digits=5, verbose_name='Preço da entrega')),
                ('delivery_method', models.CharField(choices=[('RL', 'Retirar na Loja'), ('EC', 'Entrega em Casa'), ('ED', 'Entrega Digital')], help_text='Necessário', max_length=255, verbose_name='Método de Entrega')),
                ('delivery_timeframe', models.CharField(help_text='Required', max_length=255, verbose_name='Prazo de entrega')),
                ('delivery_window', models.CharField(help_text='Necessário', max_length=255, verbose_name='Janela de entrega')),
                ('order', models.IntegerField(default=0, help_text='Necessário', verbose_name='Lista de Pedidos')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': ('Opção de entrega',),
                'verbose_name_plural': 'Opções de entrega',
            },
        ),
        migrations.CreateModel(
            name='PaymentSelections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Necessário', max_length=255, verbose_name='Nome')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Seleção de pagamento',
                'verbose_name_plural': 'Seleções de pagamento',
            },
        ),
    ]
