# Generated by Django 3.2.7 on 2023-01-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryoptions',
            options={'verbose_name': 'Delivery Option', 'verbose_name_plural': 'Delivery Options'},
        ),
        migrations.AlterModelOptions(
            name='paymentselections',
            options={'verbose_name': 'Payment Selection', 'verbose_name_plural': 'Payment Selections '},
        ),
        migrations.AlterField(
            model_name='deliveryoptions',
            name='order',
            field=models.IntegerField(default=0, help_text='Necessário', verbose_name='Ordem da Lista'),
        ),
    ]
